### ISSUE TITLE
Rename project to avoid clash with resolvo ?

### ISSUE THREAD

**Issue by jjerphan** [jerily/satdepsolver-cpp#1]
Dear @jerily,

Thank you for publishing this C++ port of `mamba-org/resolvo`!

https://github.com/mamba-org/resolvo/pull/41 introduced a [`resolvo-cpp` project](https://github.com/mamba-org/resolvo/releases/tag/resolvo_cpp-v0.1.0) which [is already distributed on conda-forge](https://github.com/conda-forge/resolvo-cpp-feedstock).

Do you think we could rename this project so that there's no reference to `resolvo`, preventing names and symbol clashes both in user's code-base and in distributions?

**Comment by jerily** [comment]
Hi @jjerphan , of course. Will do it right away. Any suggestions?

**Comment by jerily** [comment]
Changed it to satdepsolver: https://github.com/jerily/satdepsolver-cpp

Please let me know if that's ok.

**Comment by jjerphan** [comment]
Thank you for your promptness!

I do not have as much authority as you, but I would at least recommend to choose a name which is not already taken on [repology](https://repology.org/) or on GitHub.

"SATurne" is the first name which comes to my mind but [`acorrenson/SATurne`](https://github.com/acorrenson/SATurne) exists.

`satdepsolver-cpp` works for me (IMO `satdepsolver` also works).

**Comment by jerily** [comment]
Ok, thank you @jjerphan. I think we can keep satdepsolver-cpp for now.
